
services:
    nginx:
        image: 'nginx'
        volumes:
            - ./nginx/templates:/etc/nginx/templates
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            - NGINX_PORT=80
        depends_on:
            - yii2
            - frontend
        networks:
            - containers
    yii2:
        hostname: yii2.local
        build: backend
        volumes:
            - ~/.composer-docker/cache:/root/.composer/cache:delegated
            - ./backend:/app:delegated
            - ./backend/supervisor:/etc/supervisor
        environment:
            WWWUSER: '${WWWUSER}'
            DB_DSN: '${DB_DSN:-pgsql:host=db.local;dbname=test}'
            DB_USERNAME: '${DB_USERNAME:-user}'
            DB_PASSWORD: '${DB_PASSWORD:-user}'
            REDIS_HOST: 'redis.local'
            REDIS_PORT: '${FORWARD_REDIS_PORT:-6379}'
            YII_DEBUG: true
            YII_ENV: 'dev'
            RABBITMQ_HOST: '${RABBITMQ_HOST:-rabbitmq.local}'
            RABBITMQ_PORT: '${RABBITMQ_PORT:-5672}'
            RABBITMQ_USER: '${RABBITMQ_USER:-user}'
            RABBITMQ_PASSWORD: '${RABBITMQ_PASSWORD:-user}'
        networks:
            - containers
        depends_on:
            - postgres
            - redis
            - rabbitmq
    frontend:
        hostname: vue.local
        image: node:20
        ports:
            - '8888:8888'
        networks:
            - containers
        volumes:
            - ./frontend:/frontend:delegated
        command: sh -c "npm run serve"
        # command: sh -c "npm ci && npm run serve"
        working_dir: /frontend

    postgres:
        hostname: db.local
        build: db
        environment:
            POSTGRES_USER: "${POSTGRES_USER:-user}"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-user}"
            PGDATA: /var/lib/postgresql/data
        volumes:
            - postgres:/var/lib/postgresql/data
        ports:
            - "${FORWARD_REDIS_PORT:-5444}:5432"
        networks:
            - containers
    redis:
        hostname: redis.local
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'redis:/data'
        networks:
            - containers
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    rabbitmq:
        hostname: rabbitmq.local
        image: rabbitmq:3.10.7-management
        ports:
            - 15672:15672
            - 5672:5672
        networks:
            - containers
        environment:
            - RABBITMQ_DEFAULT_USER=user
            - RABBITMQ_DEFAULT_PASS=user
networks:
    containers:
        driver: bridge
volumes:
    postgres:
        driver: local
    redis:
        driver: local
